### ISSUE TITLE
The currently playing info in the queue embed is one index ahead

### ISSUE THREAD

**Issue by 11Tuvork28** [Carberra/discord.py-music-tutorial#2]
When adding a playlist, the player starts playing normal but when the queue command is invoked it shows the next song as the song currently playing.
This bug is triggered the song when the second song isn't playable.

For example if we add a playlist with 10 songs where the 2 isn't playable due to youtube then the player will start at song 0. If we now skip, the player will play song 3 but it will show us that song 2 is playing. This ends when song 3 is over and or when the 3 song is skipped to the next song.
![queue command](https://cdn.discordapp.com/attachments/664210414019674143/754678206652743730/Screenshot_from_2020-09-13_14-21-27.png)

The logs show nothing, I'm working on a fix right because I'm using your code for my bot. 

EDIT1:
Apparently there is an issues with the Queue class itself regarding the current_song function. 
I changed:
```      
From:
Line 371:   embed.add_field(name="Currently playing", value=player.queue.current_track.title, inline=False)

To:
Line 371:  embed.add_field(name="Currently playing", value=player.queue._queue[player.queue.position], inline=False)
``` 
This fixes the bug and I found out that this line change fixed another bug with the next_command but I'm gonna investigate that now.

EDIT2:
So  the best fix is I guess to just use player.queue.current_track without the accessing the tilte data because it gets displayed anyway.

**Comment by JohnnyJTH** [comment]
Ohh I never added a Playlist, if you got a fix, please show it. BTW is it just doing play then a YouTube Playlist link?

**Comment by 11Tuvork28** [comment]
@JohnnyJTH  If you mean that it can play playlist sure just do play {playlist link}

**Comment by JohnnyJTH** [comment]
> @JohnnyJTH If you mean that it can play playlist sure just do play {playlist link}

Nice never knew nor wanted to do that. But now I'm probably gonna try it 👍
