### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by IamCLY** [Carberra/discord.py-music-tutorial#5]
Thank you for the tutorial. I think my IP got banned by Youtube. Any idea on how to do this on Mac? https://ramblings.fred.moe/2020/3/tunnelbroker-with-lavalink

**Comment by nitsuga5124** [comment]
you can run lavalink on docker to be able to do this on macos

**Comment by parafoxia** [comment]
429 means you've been ratelimited. Try waiting for little while (you may have to wait until tomorrow). If that doesn't work, or you don't want to wait, try Nitsuga's solution.

**Comment by IamCLY** [comment]
It's already 4 days I believe. Any link that I can read regarding the docker? I never use that before. Thanks

**Comment by parafoxia** [comment]
Try Googling it, or find a video tutorial. I don't have any on my channel, but I'm sure there are some out there.

**Comment by nitsuga5124** [comment]
https://docs.docker.com/docker-for-mac/install/
This is the install guide

https://hub.docker.com/r/fredboat/lavalink/
and this is the docker image to use

**Comment by IamCLY** [comment]
Oh ok. Thank you. Let me try to learn it

**Comment by parafoxia** [comment]
If you have any further issues, feel free to open a case in the support server.
